<?php
/** @var \Training\HelloWorld\Block\Course $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div class="training-container">
    <h2><?= $escaper->escapeHtml($block->getTitle()) ?></h2>

    <?php if ($block->getItems()): ?>
    <ul>
        <?php foreach ($block->getItems() as $item): ?>
        <li><?= $escaper->escapeHtml($item) ?></li>
        <?php endforeach; ?>
    </ul>
    <?php else: ?>
    <p>Không có dữ liệu nào.</p>
    <?php endif; ?>
</div>
